const countryCodes = [
    ["AFG", "Afghanistan", "93"],
    ["ALB", "Albania", "355"],
    ["DZA", "Algeria", "213"],
    ["ASM", "American Samoa", "1-684"],
    ["AND", "Andorra", "376"],
    ["AGO", "Angola", "244"],
    ["AIA", "Anguilla", "1-264"],
    ["ATA", "Antarctica", "672"],
    ["ATG", "Antigua and Barbuda", "1-268"],
    ["ARG", "Argentina", "54"],
    ["ARM", "Armenia", "374"],
    ["ABW", "Aruba", "297"],
    ["AUS", "Australia", "61"],
    ["AUT", "Austria", "43"],
    ["AZE", "Azerbaijan", "994"],
    ["BHS", "Bahamas", "1-242"],
    ["BHR", "Bahrain", "973"],
    ["BGD", "Bangladesh", "880"],
    ["BRB", "Barbados", "1-246"],
    ["BLR", "Belarus", "375"],
    ["BEL", "Belgium", "32"],
    ["BLZ", "Belize", "501"],
    ["BEN", "Benin", "229"],
    ["BMU", "Bermuda", "1-441"],
    ["BTN", "Bhutan", "975"],
    ["BOL", "Bolivia", "591"],
    ["BIH", "Bosnia and Herzegovina", "387"],
    ["BWA", "Botswana", "267"],
    ["BRA", "Brazil", "55"],
    ["IOT", "British Indian Ocean Territory", "246"],
    ["VGB", "British Virgin Islands", "1-284"],
    ["BRN", "Brunei Darussalam", "1-284"],
    ["BGR", "Bulgaria", "359"],
    ["BFA", "Burkina Faso", "226"],
    ["BDI", "Burundi", "257"],
    ["KHM", "Cambodia", "855"],
    ["CMR", "Cameroon", "237"],
    ["CAN", "Canada", "1"],
    ["CPV", "Cape Verde", "238"],
    ["CYM", "Cayman Islands", "1-345"],
    ["CAF", "Central African Republic", "236"],
    ["TCD", "Chad", "235"],
    ["CHL", "Chile", "56"],
    ["CHN", "China", "86"],
    ["CXR", "Christmas Island", "61"],
    ["CCK", "Cocos Islands", "61"],
    ["COL", "Colombia", "57"],
    ["COM", "Comoros", "269"],
    ["COK", "Cook Islands", "682"],
    ["CRI", "Costa Rica", "506"],
    ["HRV", "Croatia", "385"],
    ["CUB", "Cuba", "53"],
    ["CUW", "Curaçao", "599"],
    ["CYP", "Cyprus", "357"],
    ["CZE", "Czech Republic", "420"],
    ["COD", "Democratic Republic of the Congo", "243", "DR Congo"],
    ["DNK", "Denmark", "45"],
    ["DJI", "Djibouti", "253"],
    ["DMA", "Dominica", "1-767"],
    ["DOM", "Dominican Republic", "1-809"],
    ["DOM", "Dominican Republic", "1-829"],
    ["DOM", "Dominican Republic", "1-849"],
    ["ECU", "Ecuador", "593"],
    ["EGY", "Egypt", "20"],
    ["SLV", "El Salvador", "503"],
    ["GNQ", "Equatorial Guinea", "240"],
    ["ERI", "Eritrea", "291"],
    ["EST", "Estonia", "372"],
    ["ETH", "Ethiopia", "251"],
    ["FLK", "Falkland Islands", "500"],
    ["FRO", "Faroe Islands", "298"],
    ["FJI", "Fiji", "679"],
    ["FIN", "Finland", "358"],
    ["FRA", "France", "33"],
    ["PYF", "French Polynesia", "689"],
    ["GAB", "Gabon", "241"],
    ["GMB", "Gambia", "220"],
    ["GEO", "Georgia", "995"],
    ["DEU", "Germany", "49"],
    ["GHA", "Ghana", "233"],
    ["GIB", "Gibraltar", "350"],
    ["GRC", "Greece", "30"],
    ["GRL", "Greenland", "299"],
    ["GRD", "Grenada", "1-473"],
    ["GUM", "Guam", "1-671"],
    ["GTM", "Guatemala", "502"],
    ["GGY", "Guernsey", "44-1481"],
    ["GIN", "Guinea", "224"],
    ["GNB", "Guinea-Bissau", "245"],
    ["GUY", "Guyana", "592"],
    ["HTI", "Haiti", "509"],
    ["HND", "Honduras", "504"],
    ["HKG", "Hong Kong", "852"],
    ["HUN", "Hungary", "36"],
    ["ISL", "Iceland", "354"],
    ["IND", "India", "91"],
    ["IDN", "Indonesia", "62"],
    ["IRN", "Iran", "98"],
    ["IRQ", "Iraq", "964"],
    ["IRL", "Ireland", "353"],
    ["IMN", "Isle of Man", "44-1624"],
    ["ISR", "Israel", "972"],
    ["ITA", "Italy", "39"],
    ["JAM", "Jamaica", "1-876"],
    ["JPN", "Japan", "81"],
    ["JEY", "Jersey", "44-1534"],
    ["JOR", "Jordan", "962"],
    ["KAZ", "Kazakhstan", "7"],
    ["KEN", "Kenya", "254"],
    ["KIR", "Kiribati", "686"],
    ["XKX", "Kosovo", "383"],
    ["KWT", "Kuwait", "965"],
    ["KGZ", "Kyrgyzstan", "996"],
    ["LAO", "Laos", "856"],
    ["LVA", "Latvia", "371"],
    ["LBN", "Lebanon", "961"],
    ["LSO", "Lesotho", "266"],
    ["LBR", "Liberia", "231"],
    ["LBY", "Libya", "218"],
    ["LIE", "Liechtenstein", "423"],
    ["LTU", "Lithuania", "370"],
    ["LUX", "Luxembourg", "352"],
    ["MAC", "Macao", "853"],
    ["MDG", "Madagascar", "261"],
    ["MWI", "Malawi", "265"],
    ["MYS", "Malaysia", "60"],
    ["MDV", "Maldives", "960"],
    ["MLI", "Mali", "223"],
    ["MLT", "Malta", "356"],
    ["MHL", "Marshall Islands", "692"],
    ["MRT", "Mauritania", "222"],
    ["MUS", "Mauritius", "230"],
    ["MYT", "Mayotte", "262"],
    ["MEX", "Mexico", "52"],
    ["FSM", "Micronesia", "691"],
    ["MDA", "Moldova", "373"],
    ["MCO", "Monaco", "377"],
    ["MNG", "Mongolia", "976"],
    ["MNE", "Montenegro", "382"],
    ["MSR", "Montserrat", "1-664"],
    ["MAR", "Morocco", "212"],
    ["MOZ", "Mozambique", "258"],
    ["MMR", "Myanmar", "95"],
    ["NAM", "Namibia", "264"],
    ["NRU", "Nauru", "674"],
    ["NPL", "Nepal", "977"],
    ["NLD", "Netherlands", "31"],
    ["ANT", "Netherlands Antilles", "599"],
    ["NCL", "New Caledonia", "687"],
    ["NZL", "New Zealand", "64"],
    ["NIC", "Nicaragua", "505"],
    ["NER", "Niger", "227"],
    ["NGA", "Nigeria", "234"],
    ["NIU", "Niue", "683"],
    ["PRK", "North Korea", "850"],
    ["MNP", "Northern Mariana Islands", "1-670"],
    ["NOR", "Norway", "47"],
    ["OMN", "Oman", "968"],
    ["PAK", "Pakistan", "92"],
    ["PLW", "Palau", "680"],
    ["PSE", "Palestine", "970"],
    ["PAN", "Panama", "507"],
    ["PNG", "Papua New Guinea", "675"],
    ["PRY", "Paraguay", "595"],
    ["PER", "Peru", "51"],
    ["PHL", "Philippines", "63"],
    ["PCN", "Pitcairn", "64"],
    ["POL", "Poland", "48"],
    ["PRT", "Portugal", "351"],
    ["PRI", "Puerto Rico", "1-787"],
    ["PRI", "Puerto Rico", "1-939"],
    ["QAT", "Qatar", "974"],
    ["COG", "Republic of the Congo", "242"],
    ["ROU", "Romania", "40"],
    ["RUS", "Russia", "7"],
    ["RWA", "Rwanda", "250"],
    ["BLM", "Saint Barthélemy", "590"],
    ["SHN", "Saint Helena", "290"],
    ["KNA", "Saint Kitts and Nevis", "1-869"],
    ["LCA", "Saint Lucia", "1-758"],
    ["MAF", "Saint Martin", "590"],
    ["SPM", "Saint Pierre and Miquelon", "508"],
    ["VCT", "Saint Vincent and the Grenadines", "1-784"],
    ["WSM", "Samoa", "685"],
    ["SMR", "San Marino", "378"],
    ["STP", "Sao Tome and Principe", "239"],
    ["SAU", "Saudi Arabia", "966"],
    ["SEN", "Senegal", "221"],
    ["SRB", "Serbia", "381"],
    ["SYC", "Seychelles", "248"],
    ["SLE", "Sierra Leone", "232"],
    ["SGP", "Singapore", "65"],
    ["SXM", "Sint Maarten ", "1-727"],
    ["SVK", "Slovakia", "421"],
    ["SVN", "Slovenia", "386"],
    ["SLB", "Solomon Islands", "677"],
    ["SOM", "Somalia", "252"],
    ["ZAF", "South Africa", "27"],
    ["KOR", "South Korea", "82"],
    ["SSD", "South Sudan", "211"],
    ["ESP", "Spain", "34"],
    ["LKA", "Sri Lanka", "94"],
    ["SDN", "Sudan", "249"],
    ["SUR", "Suriname", "597"],
    ["SJM", "Svalbard and Jan Mayen", "47"],
    ["SWZ", "Swaziland", "268"],
    ["SWE", "Sweden", "46"],
    ["CHE", "Switzerland", "41"],
    ["SYR", "Syria", "963"],
    ["TWN", "Taiwan", "886"],
    ["TJK", "Tajikistan", "992"],
    ["TZA", "Tanzania", "255"],
    ["THA", "Thailand", "66"],
    ["TGO", "Togo", "228"],
    ["TKL", "Tokelau", "690"],
    ["TON", "Tonga", "676"],
    ["TTO", "Trinidad and Tobago", "1-868"],
    ["TUN", "Tunisia", "216"],
    ["TUR", "Turkey", "90"],
    ["TKM", "Turkmenistan", "993"],
    ["TCA", "Turks and Caicos Islands", "1-649"],
    ["TUV", "Tuvalu", "688"],
    ["VIR", "United States Virgin Islands", "1-340", "U.S. Virgin Islands"],
    ["UGA", "Uganda", "256"],
    ["UKR", "Ukraine", "380"],
    ["ARE", "United Arab Emirates", "971"],
    ["GBR", "United Kingdom", "44"],
    ["USA", "United States of America", "1"],
    ["URY", "Uruguay", "598"],
    ["UZB", "Uzbekistan", "998"],
    ["VUT", "Vanuatu", "678"],
    ["VAT", "Vatican", "379"],
    ["VEN", "Venezuela", "58"],
    ["VNM", "Vietnam", "84"],
    ["WLF", "Wallis and Futuna", "681"],
    ["ESH", "Western Sahara", "212"],
    ["YEM", "Yemen", "967"],
    ["ZMB", "Zambia", "260"],
    ["ZWE", "Zimbabwe", "263"]
];